apiVersion: app.sealos.io/v1
kind: Instance
metadata:
  name: rustdesk-eeadyuiv
  labels:
    cloud.sealos.io/deploy-on-sealos: rustdesk-eeadyuiv
spec:
  gitRepo: https://github.com/rustdesk/rustdesk
  templateType: inline
  categories: []
  defaults:
    app_host:
      type: string
      value: jyurlkuc
    app_name:
      type: string
      value: rustdesk-eeadyuiv
  inputs:
    ENCRYPTED_ONLY:
      description: >-
        1: Restricted to secure data transmission with public key only, 0:
        Allows for unsecure data transmission
      type: choice
      options:
        - 1
        - 0
      required: true
  author: L.King
  title: RustDesk
  url: https://rustdesk.com/
  readme: >-
    https://cdn.jsdelivr.net/gh/labring-actions/templates@main/template/rustdesk/README.md
  icon: >-
    https://cdn.jsdelivr.net/gh/labring-actions/templates@main/template/rustdesk/logo.png
  description: >-
    An open-source remote desktop application designed for self-hosting, as an
    alternative to TeamViewer.
  draft: false

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rustdesk-eeadyuiv
  annotations:
    originImageName: rustdesk/rustdesk-server-s6:latest
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: rustdesk-eeadyuiv
    app: rustdesk-eeadyuiv
    cloud.sealos.io/deploy-on-sealos: rustdesk-eeadyuiv
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: rustdesk-eeadyuiv
  selector:
    matchLabels:
      app: rustdesk-eeadyuiv
  template:
    metadata:
      labels:
        app: rustdesk-eeadyuiv
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: rustdesk-eeadyuiv
          image: rustdesk/rustdesk-server-s6:latest
          env:
            - name: RELAY
              value: jyurlkuc.sealosbja.site
            - name: ENCRYPTED_ONLY
              value: '0'
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
            - containerPort: 21115
              protocol: TCP
              name: heartbeat
            - containerPort: 21116
              protocol: TCP
              name: rendezvous-tcp
            - containerPort: 21116
              protocol: UDP
              name: rendezvous-udp
            - containerPort: 21117
              protocol: TCP
              name: relay
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-data
              mountPath: /data
      volumes: []
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /data
          value: '1'
        name: vn-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: rustdesk-eeadyuiv
  labels:
    cloud.sealos.io/app-deploy-manager: rustdesk-eeadyuiv
    cloud.sealos.io/deploy-on-sealos: rustdesk-eeadyuiv
spec:
  type: NodePort
  ports:
    - protocol: UDP
      port: 21116
      targetPort: 21116
      name: rendezvous-udp
    - protocol: TCP
      port: 21116
      targetPort: 21116
      name: rendezvous-tcp
    - protocol: TCP
      port: 21117
      targetPort: 21117
      name: relay
    - protocol: TCP
      port: 21115
      targetPort: 21115
      name: heartbeat
  selector:
    app: rustdesk-eeadyuiv
